USE PFS11;

SHOW TABLES;

-- CREATE [DDL] => CREATE TABLE TABLE_NAME (
-- 	COLUNM_NAME1 DATA_TYPE CONSTRAINTS,
-- 	COLUNM_NAME2 DATA_TYPE CONSTRAINTS......
-- );
CREATE TABLE FIRST_TABLE(
	ID INT,
    STU_NAME VARCHAR(40),
    SALARY BIGINT
);

SHOW TABLES;