USE PFS11;

SHOW TABLES;

SELECT * FROM EMPLOYEES;

-- COMPARISION OPERATORS

SELECT * FROM EMPLOYEES WHERE SALARY > 35500;

SELECT * FROM EMPLOYEES WHERE SALARY < 35001;

SELECT * FROM EMPLOYEES WHERE SALARY <= 35001;

SELECT * FROM EMPLOYEES WHERE SALARY >= 35001;

SELECT * FROM EMPLOYEES WHERE SALARY = 40001;

SELECT * FROM EMPLOYEES WHERE SALARY != 40001;

-- LOGICAL OPERATORS

SELECT * FROM EMPLOYEES WHERE ID > 3;

SELECT * FROM EMPLOYEES WHERE (SALARY%2=0) AND (SALARY>40000);

SELECT * FROM EMPLOYEES WHERE (SALARY%2=0) OR (SALARY>40000);

SELECT * FROM EMPLOYEES WHERE !(SALARY%2=0);

-- NULL OPERATOS

SELECT * FROM EMPLOYEES WHERE MOBILE IS NULL;

SELECT * FROM EMPLOYEES WHERE MOBILE IS NOT NULL;


CREATE TABLE DETAILS (
	ID INT,
    FNAME VARCHAR(30),
    LNAME VARCHAR(30),
    DOB VARCHAR(12),
    AGE INT
);

DESC DETAILS;

INSERT INTO DETAILS VALUES (1,"SAI","VARDHAN","24-08-1996",30),(1,"VISHNU","VARDHAN","06-07-1998",34);

INSERT INTO DETAILS VALUES (2,"SAI","VARDHAN 1","24-08-1996",30),(3,"VISHNU","VARDHAN 2","06-07-1998",34);

INSERT INTO DETAILS VALUES (4,"SAI","VARDHAN 4","24-08-1996",30),(5,"VISHNU","VARDHAN 5","06-07-1998",34);

SELECT * FROM DETAILS;

-- CONCAT

SELECT CONCAT("SAI"," ","VARDHAN") AS FULL_NAME;

SELECT ID,CONCAT(FNAME," ",LNAME) AS FULL_NAME,AGE FROM DETAILS;

-- CONCAT_WS

SELECT CONCAT_WS(",","A","B","C","D") AS TEXT;

SELECT ID,CONCAT_WS(" ",FNAME,LNAME) AS FULL_NAME,AGE FROM DETAILS;

-- LOWER & UPPER

SELECT LOWER("AbC") AS LOWER_CASE;

SELECT UPPER("AbC") AS UPPER_CASE;

SELECT ID,LOWER(FNAME) AS FNAME,UPPER(LNAME) AS LNAME,AGE FROM DETAILS;