use pfs11;

show tables;

select * from details;

-- length

SELECT LENGTH("SAI");

SELECT LENGTH(FNAME) AS SIZE,FNAME FROM DETAILS;

-- SUBSTRING

SELECT SUBSTRING("CODEGNAN",2,5);

SELECT SUBSTRING("CODEGNAN",5);

SELECT FNAME,SUBSTRING(FNAME,2,5) FROM DETAILS;

-- REVERSE

SELECT REVERSE("SAI");

SELECT FNAME,REVERSE(FNAME) FROM DETAILS;

-- REPLACE

SELECT REPLACE("SAI","A","M");

SELECT FNAME,REPLACE(FNAME,"A","X") AS NEW_STRING FROM DETAILS;

-- LIKE

SELECT FNAME FROM DETAILS WHERE FNAME LIKE "%A%";

SELECT * FROM DETAILS;

INSERT INTO DETAILS VALUES (6,"MNO","PQR","1994",45);

SELECT * FROM DETAILS WHERE DOB LIKE "__-__-____";

DESC DETAILS;

-- CONSTRAINTS 

CREATE TABLE STUDENT100(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FULLNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(30) UNIQUE,
    MOBILE BIGINT DEFAULT 100
);

INSERT INTO STUDENT100 (FULLNAME,EMAIL,MOBILE) VALUES ("SAI","SAI@GMAIL.COM",7893570611);

SELECT * FROM STUDENT100;

INSERT INTO STUDENT100 (FULLNAME,EMAIL,MOBILE) VALUES ("SAI","SAI1@GMAIL.COM",7893570611);

SELECT * FROM STUDENT100;

INSERT INTO STUDENT100 (FULLNAME,EMAIL,MOBILE) VALUES ("SAI","SAI2@GMAIL.COM",7893570611);

SELECT * FROM STUDENT100;

TRUNCATE STUDENT100;

INSERT INTO STUDENT100 VALUES (100,"SAI","SAI@GMAIL.COM",7893570611);

INSERT INTO STUDENT100 (FULLNAME,EMAIL,MOBILE) VALUES ("SAI","SAI2@GMAIL.COM",7893570611);

INSERT INTO STUDENT100 (FULLNAME,EMAIL) VALUES ("SAI VARDHAN","SAI@GMAIL.COMMM");