USE PFS11;

CREATE TABLE FUNCTIONS (
	ID INT,
    MONEY INT,
    GIVENBY VARCHAR(30)
);

INSERT INTO FUNCTIONS VALUES (1,100,"GM"),(2,100,"GM"),(1,200,"F"),(1,200,"M"),(2,200,"F"),(3,100,"GM");

SELECT * FROM FUNCTIONS;

-- AGGREGATE FUNCTIONS

-- COUNT

SELECT COUNT(MONEY) FROM FUNCTIONS WHERE MONEY = 200;

-- SUM

SELECT SUM(MONEY) FROM FUNCTIONS WHERE ID = 1;

-- AVG

SELECT AVG(MONEY) FROM FUNCTIONS WHERE ID = 2;

-- MIN

SELECT MIN(MONEY) FROM FUNCTIONS;

-- MAX

SELECT MAX(MONEY) FROM FUNCTIONS;

-- GROUP BY

SELECT ID,SUM(MONEY) FROM FUNCTIONS GROUP BY(ID);

-- HAVING

SELECT ID,SUM(MONEY) FROM FUNCTIONS GROUP BY(ID) HAVING SUM(MONEY) > 100;

-- DATE

CREATE TABLE DATEFUNCTION(
	ID INT PRIMARY KEY,
    SIT DATE 
);

INSERT INTO DATEFUNCTION VALUES (1,"2024-08-14");


INSERT INTO DATEFUNCTION VALUES (2,"2024-08-24");

SELECT * FROM DATEFUNCTION;

-- DATE FUNCTIONS()

SELECT CURDATE();

SELECT DATE_ADD("2024-08-10",INTERVAL 3 DAY) AS UPDATED_DATE;

SELECT DATE_ADD("2024-08-10",INTERVAL 3 MONTH) AS UPDATED_DATE;

SELECT DATE_ADD("2024-08-10",INTERVAL 3 YEAR) AS UPDATED_DATE; 

SELECT DATE_SUB("2024-08-10",INTERVAL 3 DAY) AS UPDATED_DATE;

SELECT DATE_SUB("2024-08-10",INTERVAL 3 MONTH) AS UPDATED_DATE;

SELECT DATE_SUB("2024-08-10",INTERVAL 3 YEAR) AS UPDATED_DATE;

SELECT DATEDIFF("2024-09-24","2024-08-24");










